spring:
  application:
    name: sidequestlab-backend

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # ou update au début si tu veux qu'il crée les tables
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

app:
  auth:
    admin:
      email: ${ADMIN_EMAIL:}
      password: ${ADMIN_PASSWORD:}

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: ${SESSION_COOKIE_SAME_SITE:Lax}
        secure: ${SESSION_COOKIE_SECURE:false}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
